name: "tagged-release"

on:
  push:
    branches:
      - "main"
    tags:
      - "v*"

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"

    timeout-minutes: 3
    steps:
      - name: Checkout branch
        uses: "actions/checkout@v3"

      - name: Release version
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          automatic_release_tag: "latest"
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
